env:
    version: 0.1.1
    name: firefox_extension_template
    GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} 

name: firefox extension publish and sign
  
#on:
# push:
#    branches: [ master ]
# pull_request:
#    branches: [ master ]
  
jobs:
 build:
    runs-on: ubuntu-20.04
  
    steps:
    - name: Checkout Source Code
      id: checkout-source
      uses: actions/checkout@v2
    - name: Setup Node.js environment
      uses: actions/setup-node@v2.1.2
      with:
        # Version Spec of the version to use.  Examples: 12.x, 10.15.1, >=10.15.0
        node-version: 12.x
        # Set this option if you want the action to check for the latest available version that satisfies the version spec
        check-latest: true
    - name: Npm init and build
      run: |
        npm install -g webpack-cli
        npm install -g web-ext
        npm install
        npm run build
    - name: web-ext sign package
      run: web-ext sign --source-dir ./dist -v --api-key=${{ secrets.WEB_EXT_API_KEY }} --api-secret=${{ secrets.WEB_EXT_API_SECRET }}
    - name: Delete tag and release
      id: delete-tag-release
      uses: dev-drprasad/delete-tag-and-release@v0.1.2
      with:
        tag_name: ${{ env.version }}
        delete_release: true
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ env.version }}
        release_name: Release ${{ github.repository }}-${{ env.version }}
        body: check the commits for update
        draft: false
        prerelease: false
    - name: Upload Release firefox extension
      id: upload-release-asset-jar
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps
        asset_path: ./web-ext-artifacts/${{env.name}}-${{env.version}}-an+fx.xpi
        asset_name: ${{env.name}}-${{env.version}}-an+fx.xpi
        asset_content_type: application/x-xpinstall
